runtime: nodejs20
service: default
instance_class: F2

handlers:
  - url: /static
    static_dir: static

  - url: /
    static_files: index.html
    upload: index.html

  - url: /.* 
    static_files: index.html
    upload: index.html

env_variables:
  NODE_ENV: 'production'
