runtime: nodejs22

instance_class: F1

env_variables:
  NODE_ENV: production

handlers:
  # Handle root (/) request ke index.html
  - url: /
    static_files: index.html
    upload: index.html

  # Handle semua file di root folder (seperti login.html, register.html, style.css, dll)
  - url: /(.*)
    static_files: \1
    upload: (.*)

entrypoint: node app.js

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 3
